# Site settings
title: Nich - Technology & Marketing Solutions - uALREADY LLC
email: 
description: > # this means to ignore newlines until "baseurl:"
  Nich x uALREADY LLC x Nicholas Resendez
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nich.online" # the base hostname & protocol for your site
twitter_username: bothersome
github_username: nirholas

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
